FROM ubuntu:trusty

MAINTAINER chosenbreed37 <chosenbreed@gmail.com>

# update packages
RUN apt-get update

# install vim
RUN apt-get install -y --force-yes vim

# install tree
RUN apt-get install -y --force-yes tree

# install git
RUN apt-get install -y --force-yes git

# install curl
RUN apt-get install -y --force-yes curl

# install nodejs
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN apt-get install -y --force-yes  nodejs

# install standardjs
RUN npm install -g standard

# install standardjs auto formatting on save
RUN npm install -g standard-format

# install pathogen
RUN mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# add entry to ~/.vimrc
RUN echo "execute pathogen#infect()" >> ~/.vimrc

# install syntastic as a pathogen bundle
RUN cd ~/.vim/bundle && git clone https://github.com/scrooloose/syntastic.git

# add entry to ~/.vimrc
RUN echo "let g:syntastic_javascript_checkers = ['standard']" >> ~/.vimrc
RUN echo "autocmd bufwritepost *.js silent !standard-format -w %" >> ~/.vimrc
RUN echo "set autoread" >> ~/.vimrc

# install linkchecker
RUN apt-get install -y --force-yes linkchecker

# install grunt cli
RUN npm install -g grunt-cli

# expose port 8000
EXPOSE 8000


